schema_version: 1

context:
  name: aws-c-sdkutils
  version: "0.2.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/awslabs/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: 14fe900f80c3b9f5e53a783d9ac0865ed9ba1ae63b67744b9f82a8b3194a4388

build:
  number: 1

requirements:
  build:
    - cmake !=3.19.0,!=3.19.1
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ninja
  host:
    - aws-c-common
  run_exports:
    - ${{ pin_subpackage("aws-c-sdkutils", upper_bound="x.x.x") }}

tests:
  - script:
      - if: unix
        then:
          - test -f $PREFIX/lib/libaws-c-sdkutils${SHLIB_EXT}
          - test -f $PREFIX/include/aws/sdkutils/sdkutils.h
      - if: win
        then:
          - if not exist %LIBRARY_INC%\\aws\\sdkutils\\sdkutils.h exit 1
          - if not exist %PREFIX%\\Library\\bin\\aws-c-sdkutils.dll exit 1
about:
  license: Apache-2.0
  license_file: LICENSE
  summary: This is a module for the AWS SDK for C.
  homepage: https://github.com/awslabs/aws-c-sdkutils
  repository: https://github.com/awslabs/aws-c-sdkutils

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
